### ISSUE TITLE
Error with DICTOL_test: myinit.m potentially not adding all relevant paths

### ISSUE THREAD

**Issue by mefathy** [tiepvupsu/DICTOL#1]
It seems that myinit.m does not add all relevant directories to path via addpath. I get an error when I run DICTOL_test with MATLAB 2015a. Based on the error message, ODL is undefined. When I addpath('ODL') after myinit.m and before running DICTOL_test, I do not get that error.

**Comment by tiepvupsu** [comment]
Thank you for specifying that error. 

I just added "addpath('ODL')" so now the error is fixed.

**Comment by mefathy** [comment]
We are also grateful for the nice project. By the way, as DICTOL_test ends, I got the following error:

Error in DICTOL_test (line 82)                                         
fprintf('|  LCKSVD1   |   %2.2f%%    |\n', 100*acc_lcksvd(1));         

Apparently, acc_lcksvd, which is supposed to hold the accuracy of LCKSVD, has not been defined before.

**Comment by tiepvupsu** [comment]
HI @mefathy, I didn't include LCKSVD here since I commented LCKSVD part, but forgot to comment its results. For LCKSVD, you can find its source code from the original website: 
https://www.umiacs.umd.edu/~zhuolin/projectlcksvd.html

Thank you.
