### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by secondsensei** [tiepvupsu/DICTOL#3]
1. Y is a size 2000x50 matrix. Should this be transposed?

2. k, and lambda are defined variables. What are my options for _opts_?

3.

`>> ODL(Y, k, lambda, opts, 'fista')
Unable to perform assignment because dot indexing is not supported for variables of this type.

Error in initOpts (line 14)
        opts.verbose = 0;

Error in ODL (line 36)
	opts = initOpts(opts);`

When I ran the function. I got this error. Please assist

**Comment by tiepvupsu** [comment]
1. Y should be in shape [n_features, n_samples], which mean each *column* is a sample.

2. k and lambda should be chosen based on each problem and data. k must be << n_samples lambda should be < 1 (0.1, 0.01).
3. I don't have matlab now, not sure how I could assist you.

**Comment by secondsensei** [comment]
Thanks for the response. What about the 'opts' input? What can I input for 'opts'?
ODL(Y, k, lambda, **_opts_**, 'fista')

**Comment by tiepvupsu** [comment]
Please see the [source code](https://github.com/tiepvupsu/DICTOL/blob/master/ODL/ODL.m#L28-L32) for more information.
